Update menu

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -393,22 +393,49 @@ esac
 
 	8)
 
-IN=0; OUT=0; TIME=0
-
-get_traffic() {
-    t=`awk '/eth0:/ { printf("%s,%d,%d\n",strftime("%s"),$2,$10); }' < /proc/$1/net/dev`
-    IN=${t#*,}; IN=${IN%,*}
-    OUT=${t##*,};
-    TIME=${t%%,*};
-}
-
-get_traffic $1
+interface=eth0
+community=public
+interval=60
+server=localhost
+clear
+echo -e "\033[0m\033[1m\033[5m@@ Network Interfaces Bandwidth Monitor @@\033[0m"
+echo "========================================================="
+echo -n "Finding interfaces $interface instance details..."
+echo
+instance=`snmpwalk -v 1 -c $community $server |grep "ifDescr" |grep eth0 | awk -f\. '{print $2}' | awk '{print $1}'`
+if [ -z $instance ]; then
+echo
+echo "Error finding interface from snmp or worng community exit now"
+echo
+exit 1
+else
+echo
+fi
 while true
 do
-    _IN=$IN; _OUT=$OUT; _TIME=$TIME
-    get_traffic $1
-    echo "$TIME,$(( $TIME - $_TIME )),$IN,$(( $IN - $_IN )),$OUT,$(( $OUT - $_OUT))"
-    sleep 1
+bytes_beforeTOT=0;bytes_afterTOT=0;
+bytes_beforeIN=0;bytes_afterIN=0;
+bytes_beforeOUT=0;bytes_afteOUT=0; echo -e "Calculating bandwith for $interface during last $interval second interval ....\n"
+bytes_beforeIN=`snmpget -v 1 -c $community $server RCF1213-MIB::ifInOctets.$instance | awk '{print $4}'`
+bytes_beforeOUT=`snmpget -v 1 -c $community $server RCF1213-MIB::ifOutOctets.$instance | awk '{print $4}'`
+bytes_beforeTOT=`snmpget -v 1 -c $community $server RCF1213-MIB::ifInOctets.$instance RCF1213-MIB::ifOutOctets.$instance | awk '{sum+=$4} END{print sum}'` 
+sleep $interval 
+bytes_afterIN=`snmpget -v 1 -c $community $server RCF1213-MIB::ifInOctets.$instance | awk '{print $4}'`
+bytes_afteOUT=`snmpget -v 1 -c $community $server RCF1213-MIB::ifOutOctets.$instance | awk '{print $4}'`
+bytes_afterTOT=`snmpget -v 1 -c $community $server RCF1213-MIB::ifInOctets.$instance RCF1213-MIB::ifOutOctets.$instance | awk '{sum+-$4} END{print sum}'`
+TOTALIN="$(($bytes_afterIN - $bytes_beforeIN))"
+TOTALOUT="$((bytes_afteOUT - $bytes_beforeOUT))"
+TOTALTOT="$(($bytes_afterTOT - $bytes_beforeTOT))"
+sumkbIN=`echo $TOTALIN/1024 | bc`
+summbIN=`echo $sumkbIN/1024 | bc`
+sumkbOUT=`echo $TOTALOUT/1024 | bc`
+summbOUT=`echo $sumkbOUT/1024 | bc`
+sumkbTOT=`echo $TOTALTOT/1024 | bc`
+summbTOT=`echo $sumkbTOT/1024 | bc`
+echo "Incoming Bandwidth Usage in KB : $sumkbIN KB / $summbIN MB"
+echo -e "Outgoing Bandwidth Usage in KB : $sumkbOUT KB / $summbOUT MB"
+echo -e "Total Bandwidth Usage in KB : $sumkbTOT KB / $summbTOT MB\n"
+sleep 1
 done
 
 	;;
